//Error code definitions
#define APP_ERROR_NONE 0
#define APP_ERROR_UNDEFINED 1

#define APP_ERROR_GLFW_INIT 2
#define APP_ERROR_GLFW_WINDOW 3

#define APP_ERROR_BASS_INIT 4

#define APP_ERROR_GLEW_INIT 5

#define APP_ERROR_MUSIC_MODULE_UNDEFINED 6
#define APP_ERROR_PLAYLIST_INVALID 7